  services:
    postgres:
      image: postgres:17
      container_name: go_postgres
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        timeout: 5s
        retries: 5

    pgadmin:
      image: dpage/pgadmin4:8.12
      container_name: go_pgadmin
      restart: always
      profiles: ["tools"]
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      ports:
        - "5050:80"
      depends_on:
        postgres:
          condition: service_healthy

    redis:
      image: redis:7-alpine
      container_name: go_redis
      restart: always
      environment:
        REDIS_PASSWORD: ${REDIS_PASSWORD}
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
      ports:
        - "6379:6379"
      healthcheck:
        test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

    mongo:
      image: mongo:6
      container_name: go_mongo
      restart: always
      profiles: ["tools"]
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ports:
        - "27017:27017"
      volumes:
        - mongo_data:/data/db
      healthcheck:
        # use mongosh (bundled in mongo:6) to run a quiet ping against admin DB
        test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand({ping:1})"]
        interval: 10s
        timeout: 5s
        retries: 5

    mongo-express:
      image: mongo-express:1.0.0
      container_name: go_mongo_express
      restart: always
      profiles: ["tools"]
      environment:
        ME_CONFIG_MONGODB_SERVER: mongo
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        # explicit auth DB and full connection URL help when authentication is enabled
        ME_CONFIG_MONGODB_AUTH_DATABASE: admin
        ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/admin"
      ports:
        - "8081:8081"
      depends_on:
        mongo:
          condition: service_healthy

  volumes:
    postgres_data:
    mongo_data:
